#!/bin/bash

#=== Cấu hình ===#
SAMPLE_NAME="sample01"
READ1="raw_data/${SAMPLE_NAME}_R1.fq.gz"
READ2="raw_data/${SAMPLE_NAME}_R2.fq.gz"
REF="/media/shmily/writable/BRCA_project/reference/GRCh38.fa"
KNOWN_SITES_DIR="/media/shmily/writable/BRCA_project/reference/known_sites"
OUTDIR="results/${SAMPLE_NAME}_trimmed"
INTERVAL="/media/shmily/writable/BRCA_project/reference/scattered.interval_list"

mkdir -p ${OUTDIR}

#=== Step 1: Quality trimming + cut 2 bases đầu, giữ 140 ===#
conda activate BRCA
trimmomatic PE -threads 8 \
  ${READ1} ${READ2} \
  ${OUTDIR}/${SAMPLE_NAME}_R1_paired.fq.gz ${OUTDIR}/${SAMPLE_NAME}_R1_unpaired.fq.gz \
  ${OUTDIR}/${SAMPLE_NAME}_R2_paired.fq.gz ${OUTDIR}/${SAMPLE_NAME}_R2_unpaired.fq.gz \
  HEADCROP:2 CROP:140 SLIDINGWINDOW:4:20 MINLEN:36

#=== Các bước sau giữ nguyên như script 1 ===#
bwa mem -t 8 -M ${REF} \
  ${OUTDIR}/${SAMPLE_NAME}_R1_paired.fq.gz ${OUTDIR}/${SAMPLE_NAME}_R2_paired.fq.gz \
  > ${OUTDIR}/${SAMPLE_NAME}.sam

samtools view -bS ${OUTDIR}/${SAMPLE_NAME}.sam | samtools sort -o ${OUTDIR}/${SAMPLE_NAME}_sorted.bam
rm ${OUTDIR}/${SAMPLE_NAME}.sam

picard MarkDuplicates \
  I=${OUTDIR}/${SAMPLE_NAME}_sorted.bam \
  O=${OUTDIR}/${SAMPLE_NAME}_marked.bam \
  M=${OUTDIR}/${SAMPLE_NAME}_metrics.txt

samtools index ${OUTDIR}/${SAMPLE_NAME}_marked.bam

conda activate GATK

gatk BaseRecalibrator \
  -I ${OUTDIR}/${SAMPLE_NAME}_marked.bam \
  -R ${REF} \
  --known-sites ${KNOWN_SITES_DIR}/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
  --known-sites ${KNOWN_SITES_DIR}/Homo_sapiens_assembly38.dbsnp138.vcf.gz \
  -O ${OUTDIR}/recal_data.table

gatk ApplyBQSR \
  -R ${REF} \
  -I ${OUTDIR}/${SAMPLE_NAME}_marked.bam \
  --bqsr-recal-file ${OUTDIR}/recal_data.table \
  -O ${OUTDIR}/${SAMPLE_NAME}_recal.bam

gatk HaplotypeCaller \
  -R ${REF} \
  -I ${OUTDIR}/${SAMPLE_NAME}_recal.bam \
  -O ${OUTDIR}/${SAMPLE_NAME}.g.vcf.gz \
  -ERC GVCF \
  -L ${INTERVAL}

conda activate BRCA
mosdepth ${OUTDIR}/${SAMPLE_NAME} ${OUTDIR}/${SAMPLE_NAME}_recal.bam
depvariance ${OUTDIR}/${SAMPLE_NAME}.mosdepth.global.dist.txt > ${OUTDIR}/${SAMPLE_NAME}_coverage_stats.txt
